name: pspio
version: '0.2.0'
summary: Library to read and write pseudopotentials in multiple formats
description: |
  Pspio performs I/O from and to pseudopotential data files so that users
  do not have to care about the associated specifications. It can be used
  to convert between pseudopotential formats to a very limited extent,
  when both formats store the exact same quantities.

grade: devel
confinement: devmode

parts:
  esl-pspio:
    plugin: autotools
    stage-packages:
      - autoconf-archive
      - check
      - libxml2-dev

