
name: pspio # you probably want to 'snapcraft register <name>'
version: '0.2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Library to read and write pseudopotentials in multiple formats
description: |
  Pspio performs I/O from and to pseudopotential data files so that users
  do not have to care about the associated specifications. It can be used
  to convert between pseudopotential formats to a very limited extent,
  when both formats store the same quantities.

grade: devel
confinement: devmode

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: autotools
